/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical scaffolds and kept here so
// TypeScript understands Next's ambient types before the first dev run.
